eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/,http://127.0.0.1:1113/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5   # Make sure eureka server can detect whether this app is up or down. Add by Zhang Chao.
    lease-expiration-duration-in-seconds: 5